import type { Metadata } from 'next'
import { Poppins, Noto_Sans } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
})

const notoSans = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'TESTAPP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${poppins.variable} ${notoSans.variable} font-sans antialiased bg-surface`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
